---
sub_group: "{visit_date}"
fields:
  - template: "Last vaccine Doses Given: {antigen_administered_last}"
    relevance: "antigen_administered_last != ''"


  - template: "Date Last Vaccine was Given: {administration_date}"
    relevance: "administration_date != ''"


  - template: "Missed (Vaccine) Antigen Doses: {missed_doses}"
    relevance: "missed_doses != ''"
    isHtml: true

  - template: "Date Client Was Expected to Return: {return_date}"
    relevance: "return_date != ''"
    isHtml: true

  - template: "Name of CHV Assigned: {chv_name}"
    relevance: "chv_name != ''"
    isHtml: true

  - template: "Phone Number of CHV Assigned: {chv_phone_number}"
    relevance: "chv_phone_number != ''"
    isHtml: true

  - template: "Phone Tracing: {phone_tracing}"
    relevance: "phone_tracing != ''"
    isHtml: true

  - template: "Conducted a Physical Visit for Unreachable Client?: {physical_tracing}"
    relevance: "physical_tracing != ''"
    isHtml: true

  - template: "Phone Tracing Outcome: {phone_tracing_outcome}"
    relevance: "phone_tracing_outcome != ''"
    isHtml: true

  - template: "Physical Visit Tracing Outcome: {physical_tracing_outcome}"
    relevance: "physical_tracing_outcome != ''"
    isHtml: true

  - template: "Home Vaccine Administration Date: {home_administration_date}"
    relevance: "home_administration_date != ''"
    isHtml: true

  - template: "Other Facility Name: {other_facility_name}"
    relevance: "other_facility_name != ''"
    isHtml: true

  - template: "Other Facility Date Vaccine was Given: {other_facility_administration_date}"
    relevance: "other_facility_administration_date != ''"
    isHtml: true

  - template: "Proposed Date to come for Vaccine by Client: {date_to_confirm_vaccination}"
    relevance: "date_to_confirm_vaccination != ''"
    isHtml: true


  - template: "Last Covid vaccine Given: {covid_antigen_administered_last}"
    relevance: "covid_antigen_administered_last != ''"


  - template: "Date Last Covid Vaccine was Given: {covid_administration_date}"
    relevance: "covid_administration_date != ''"


  - template: "Missed Covid (Vaccine) Antigen: {covid_missed_doses}"
    relevance: "covid_missed_doses != ''"
    isHtml: true

  - template: "Date Client Was Expected to Return: {covid_return_date}"
    relevance: "covid_return_date != ''"
    isHtml: true

  - template: "Name of CHV Assigned: {covid_chv_name}"
    relevance: "covid_chv_name != ''"
    isHtml: true

  - template: "Phone Number of CHV Assigned: {covid_chv_phone_number}"
    relevance: "covid_chv_phone_number != ''"
    isHtml: true

  - template: "Phone Tracing: {covid_phone_tracing}"
    relevance: "covid_phone_tracing != ''"
    isHtml: true

  - template: "Conducted a Physical Visit for Unreachable Client?: {covid_physical_tracing}"
    relevance: "covid_physical_tracing != ''"
    isHtml: true

  - template: "Covid Phone Tracing Outcome: {covid_phone_tracing_outcome}"
    relevance: "covid_phone_tracing_outcome != ''"
    isHtml: true

  - template: "Covid Physical Visit Tracing Outcome: {covid_physical_tracing_outcome}"
    relevance: "covid_physical_tracing_outcome != ''"
    isHtml: true

  - template: "Home Vaccine Administration Date: {covid_home_administration_date}"
    relevance: "covid_home_administration_date != ''"
    isHtml: true

  - template: "Other Facility Name: {covid_other_facility_name}"
    relevance: "covid_other_facility_name != ''"
    isHtml: true

  - template: "Other Facility Date Vaccine was Given: {covid_other_facility_administration_date}"
    relevance: "covid_other_facility_administration_date != ''"
    isHtml: true

  - template: "Proposed Date to come for Vaccine by Client: {covid_date_to_confirm_vaccination}"
    relevance: "covid_date_to_confirm_vaccination != ''"
    isHtml: true


