---
group:
sub_group: Last_Vaccine_Given
fields:
  - template: "Last Vaccine (Antigen) Doses Given: {antigen_administered_last}"
    relevance: "antigen_administered_last != ''"

  - template: "Date Last Vaccine (Antigen) Given: {administration_date}"
    relevance: "administration_date != ''"

  - template: "Birth Doses: {last_birth_dose_antigen}"
    relevance: "last_birth_dose_antigen != ''"

  - template: "Six Weeks Doses: {last_six_wks_antigen}"
    relevance: "last_six_wks_antigen != ''"

  - template: "Ten Weeks Doses: {last_ten_wks_antigen}"
    relevance: "last_ten_wks_antigen != ''"

  - template: "Fourteen Weeks Doses: {last_fourteen_wks_antigen}"
    relevance: "last_fourteen_wks_antigen != ''"

  - template: "Nine Months Doses: {last_nine_months_antigen}"
    relevance: "last_nine_months_antigen != ''"

  - template: "Eighteen Months Doses: {last_eighteen_months_antigen}"
    relevance: "last_eighteen_months_antigen != ''"
---
group:
sub_group: Missed_Vaccine
fields:
  - template: "Missed (Vaccine) Antigen Doses: {missed_doses}"
    relevance: "missed_doses != ''"

  - template: "Date Client Was Expected to Return: {return_date}"
    relevance: "return_date != ''"

---
group:
sub_group: CHV_Details
fields:
  - template: "Name of CHV Assigned: {chv_name}"
    relevance: "chv_name != ''"

  - template: "Phone Number of CHV Assigned: {chv_phone_number}"
    relevance: "chv_phone_number != ''"

---
group:
sub_group: Mode_of_Tracing
fields:

  - template: "Phone Tracing: {phone_tracing}"
    relevance: "phone_tracing != ''"

  - template: "Conducted a Physical Visit for Unreachable Client?: {physical_tracing}"
    relevance: "physical_tracing != ''"

  - template: "Reason Not conduct a physical visit: {reason_not_conduct_physical_visit}"
    relevance: "reason_not_conduct_physical_visit != ''"

---
sub_group: Tracing_Outcome
fields:
  - template: "Phone Tracing Outcome: {phone_tracing_outcome}"
    relevance: "phone_tracing_outcome != ''"

  - template: "Physical Visit Tracing Outcome: {physical_tracing_outcome}"
    relevance: "physical_tracing_outcome != ''"

  - template: "Home Vaccine Administration Date: {home_administration_date}"
    relevance: "home_administration_date != ''"

  - template: "Other Facility Name: {other_facility_name}"
    relevance: "other_facility_name != ''"

  - template: "Other Facility Administration Date: {other_facility_administration_date}"
    relevance: "other_facility_administration_date != ''"

  - template: "Proposed Date to come for Vaccine by Client: {date_to_confirm_vaccination}"
    relevance: "date_to_confirm_vaccination != ''"
